replicaCount: 2

image:
  repository: 577638384428.dkr.ecr.us-east-2.amazonaws.com/dcli-sn
  tag: dk-sn
  pullPolicy: Always

imagePullSecrets: []
  - name: regcred
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
